---
- hosts: all
  gather_facts: no
  pre_tasks:
  - name: install python2
    # https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f
    raw: test -e /usr/bin/python2.7 || (apt-get -y update && apt-get install -y python2.7)
    become: yes
  
  tasks:
  - name: install cmake
    apt:
      name: "{{item}}"
      state: present
    become: true
    with_items:
      - cmake
      - g++
      - make
      - git
